### PR TITLE
1136/get scored variants

### PR DESCRIPTION
**Pull request by coldzonemt**
A method that allows users to get the scored variants from a report. I needed to write this so that I could write a test.

### CODE REVIEW

**Review by milotoor — APPROVED** [review]

**Comment by apfejes** [comment]
I have a feeling I should be removed from this repo.....  (-:  Though, glad you can get scored variants from a report!  +1

**Comment by milotoor** [comment]
@apfejes this is a public repo, so you'll have to "Unwatch" it. Also hi!

**Comment by coldzonemt** [comment]
hi, @apfejes !

**Comment by apfejes** [comment]
Thanks Marco - Hi Everyone... and bye too.  (Repo Unwatched.)

**Pull request merged**
